<!--
%\VignetteEngine{knitr::docco_classic}
%\VignetteIndexEntry{rebird vignette}
-->

# Intro to the rebird package

A programmatic interface to the eBird database. Find out more about eBird at [their website](http://ebird.org/home/).

## Installation

You can install the stable version from CRAN


```r
install.packages("rebird")
```

Or the development version from Github


```r
install.packages("devtools")
devtools::install_github("ropensci/rebird")
```

Then load the package into the R sesssion


```r
library("rebird")
```

## Usage

The [eBird API server](https://documenter.getpostman.com/view/664302/S1ENwy59?version=latest) 
has been updated and thus there are a couple major changes in the way `rebird` works.
API requests to eBird now require users to provide an API key, which is linked to your 
eBird user account. 
You can pass it to the 'key' argument in `rebird` functions, but we highly recommend
storing it as an environment variable called EBIRD_KEY in your .Renviron file.
If you don't have a key, you can obtain one from <https://ebird.org/api/keygen>.

You can keep your .Renviron file in your global R home directory (`R.home()`), your user's home
directory (`Sys.getenv("HOME")`), or your current working directory (`getwd()`). Remember
that .Renviron is loaded once when you start R, so if you add your API key to the file you will
have to restart your R session. See <https://csgillespie.github.io/efficientR/r-startup.html> for
more information on R's startup files.

Furthermore, functions now use species codes, rather than scientific names, for species-specific requests.
We've made the switch easy by providing the `species_code` function, which converts a scientific name to
its species code:


```r
species_code('sula variegata')
```

```
## Peruvian Booby (Sula variegata): perboo1
```

```
## [1] "perboo1"
```

The `species_code` function can be called within other `rebird` functions, or the species code 
can be specified directly.

### Sightings at location determined by latitude/longitude

Search for bird occurrences by latitude and longitude point


```r
ebirdgeo(species = species_code('spinus tristis'), lat = 42, lng = -76)
```

```
## American Goldfinch (Spinus tristis): amegfi
```

```
## # A tibble: 44 x 13
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 amegfi      Americ… Spinus… L107… 2403 S… 2020…       8  41.9 -75.8
##  2 amegfi      Americ… Spinus… L116… Bruce … 2020…      12  41.9 -75.8
##  3 amegfi      Americ… Spinus… L229… Imperi… 2020…       1  42.1 -76.0
##  4 amegfi      Americ… Spinus… L223… 9 Chri… 2020…       4  42.1 -75.9
##  5 amegfi      Americ… Spinus… L116… Lamour… 2020…      NA  42.1 -76.0
##  6 amegfi      Americ… Spinus… L197… esther… 2020…       3  42.1 -75.9
##  7 amegfi      Americ… Spinus… L275… "Home " 2020…       5  42.1 -76.0
##  8 amegfi      Americ… Spinus… L611… Hillcr… 2020…       2  42.1 -75.9
##  9 amegfi      Americ… Spinus… L978… Murphy… 2020…       5  42.1 -76.0
## 10 amegfi      Americ… Spinus… L110… 913 Ch… 2020…       2  42.1 -76.0
## # … with 34 more rows, and 4 more variables: obsValid <lgl>,
## #   obsReviewed <lgl>, locationPrivate <lgl>, subId <chr>
```

Same, but with additional parameter settings, returning only 10 records, including provisional records, and hotspot records. 


```r
ebirdgeo(lat = 42, lng = -76, max = 10, includeProvisional = TRUE, hotspot = TRUE)
```

```
## # A tibble: 10 x 13
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 cangoo      Canada… Branta… L274… River … 2020…       3  42.1 -76.0
##  2 wooduc      Wood D… Aix sp… L274… River … 2020…      24  42.1 -76.0
##  3 buwtea      Blue-w… Spatul… L274… River … 2020…       5  42.1 -76.0
##  4 mallar3     Mallard Anas p… L274… River … 2020…       6  42.1 -76.0
##  5 pibgre      Pied-b… Podily… L274… River … 2020…       1  42.1 -76.0
##  6 horgre      Horned… Podice… L274… River … 2020…       1  42.1 -76.0
##  7 killde      Killde… Charad… L274… River … 2020…       3  42.1 -76.0
##  8 doccor      Double… Phalac… L274… River … 2020…       5  42.1 -76.0
##  9 turvul      Turkey… Cathar… L274… River … 2020…       4  42.1 -76.0
## 10 dowwoo      Downy … Dryoba… L274… River … 2020…       2  42.1 -76.0
## # … with 4 more variables: obsValid <lgl>, obsReviewed <lgl>,
## #   locationPrivate <lgl>, subId <chr>
```


### Recent sightings from location IDs

Search for bird occurrences for in a hotspot using its ID


```r
ebirdregion(loc = 'L99381')
```

```
## # A tibble: 74 x 13
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 nrwswa      Northe… Stelgi… L993… Stewar… 2020…       1  42.5 -76.5
##  2 cangoo      Canada… Branta… L993… Stewar… 2020…      14  42.5 -76.5
##  3 wooduc      Wood D… Aix sp… L993… Stewar… 2020…       1  42.5 -76.5
##  4 norsho      Northe… Spatul… L993… Stewar… 2020…       1  42.5 -76.5
##  5 mallar3     Mallard Anas p… L993… Stewar… 2020…       4  42.5 -76.5
##  6 rinduc      Ring-n… Aythya… L993… Stewar… 2020…       2  42.5 -76.5
##  7 lessca      Lesser… Aythya… L993… Stewar… 2020…      12  42.5 -76.5
##  8 buffle      Buffle… Buceph… L993… Stewar… 2020…      32  42.5 -76.5
##  9 rudduc      Ruddy … Oxyura… L993… Stewar… 2020…      11  42.5 -76.5
## 10 rocpig      Rock P… Columb… L993… Stewar… 2020…       1  42.5 -76.5
## # … with 64 more rows, and 4 more variables: obsValid <lgl>,
## #   obsReviewed <lgl>, locationPrivate <lgl>, subId <chr>
```

Search by location ID and species name, as well as some additional parameter settings 


```r
ebirdregion(loc = 'L99381', species = species_code('larus delawarensis'), 
         max = 10, provisional = TRUE, hotspot = TRUE)
```

```
## Ring-billed Gull (Larus delawarensis): ribgul
```

```
## # A tibble: 1 x 13
##   speciesCode comName sciName locId locName obsDt howMany   lat   lng
##   <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
## 1 ribgul      Ring-b… Larus … L993… Stewar… 2020…       2  42.5 -76.5
## # … with 4 more variables: obsValid <lgl>, obsReviewed <lgl>,
## #   locationPrivate <lgl>, subId <chr>
```


## Nearest observations of a species

Search for a species' occurrences near a given latitude and longitude


```r
nearestobs(species_code('branta canadensis'), 42, -76)
```

```
## Canada Goose (Branta canadensis): cangoo
```

```
## # A tibble: 59 x 13
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 cangoo      Canada… Branta… L274… River … 2020…       3  42.1 -76.0
##  2 cangoo      Canada… Branta… L247… Conflu… 2020…       5  42.1 -75.9
##  3 cangoo      Canada… Branta… L166… Chugnu… 2020…       5  42.1 -76.0
##  4 cangoo      Canada… Branta… L100… Brick … 2020…       1  42.1 -76.2
##  5 cangoo      Canada… Branta… L111… 526 Co… 2020…       1  42.0 -76.0
##  6 cangoo      Canada… Branta… L116… Murphy… 2020…       4  42.1 -76.0
##  7 cangoo      Canada… Branta… L453… Waterm… 2020…       6  42.1 -76.2
##  8 cangoo      Canada… Branta… L505… Boland… 2020…      18  42.2 -75.9
##  9 cangoo      Canada… Branta… L978… Murphy… 2020…      11  42.1 -76.0
## 10 cangoo      Canada… Branta… L201… Conflu… 2020…      15  42.1 -76.3
## # … with 49 more rows, and 4 more variables: obsValid <lgl>,
## #   obsReviewed <lgl>, locationPrivate <lgl>, subId <chr>
```


### Recent observations at a region

Search for bird occurrences by region and species name


```r
ebirdregion(loc = 'US', species = species_code('Setophaga caerulescens'))
```

```
## Black-throated Blue Warbler (Setophaga caerulescens): btbwar
```

```
## # A tibble: 57 x 13
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 btbwar      Black-… Setoph… L127… Mead B… 2020…       1  28.6 -81.4
##  2 btbwar      Black-… Setoph… L567… "Palme… 2020…       1  28.9 -81.3
##  3 btbwar      Black-… Setoph… L110… 8220 S… 2020…       1  25.6 -80.3
##  4 btbwar      Black-… Setoph… L111… Cherry… 2020…       1  35.3 -82.8
##  5 btbwar      Black-… Setoph… L542… Indian… 2020…       1  26.5 -80.1
##  6 btbwar      Black-… Setoph… L816… Kissim… 2020…       1  27.6 -81.0
##  7 btbwar      Black-… Setoph… L722… Sereno… 2020…       2  26.4 -80.1
##  8 btbwar      Black-… Setoph… L339… Flat T… 2020…       2  35.6 -82.4
##  9 btbwar      Black-… Setoph… L558… Pine W… 2020…       1  25.6 -80.4
## 10 btbwar      Black-… Setoph… L336… Wildwo… 2020…       1  27.9 -81.8
## # … with 47 more rows, and 4 more variables: obsValid <lgl>,
## #   obsReviewed <lgl>, locationPrivate <lgl>, subId <chr>
```

Search by location ID and species name, as well as some additional parameter settings. Note that we use `US-OH` to represent Ohio within the US.


```r
ebirdregion(loc = 'US-OH', max = 10, provisional = TRUE, hotspot = TRUE)
```

```
## # A tibble: 10 x 13
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 amewoo      Americ… Scolop… L107… Blue H… 2020…       7  41.4 -83.0
##  2 cangoo      Canada… Branta… L107… Blue H… 2020…       2  41.4 -83.0
##  3 fiespa      Field … Spizel… L107… Blue H… 2020…       2  41.4 -83.0
##  4 sonspa      Song S… Melosp… L107… Blue H… 2020…       1  41.4 -83.0
##  5 grhowl      Great … Bubo v… L107… Blue H… 2020…       1  41.4 -83.0
##  6 killde      Killde… Charad… L107… Blue H… 2020…       2  41.4 -83.0
##  7 amerob      Americ… Turdus… L107… Blue H… 2020…       5  41.4 -83.0
##  8 moudov      Mourni… Zenaid… L220… Union … 2020…       2  40.0 -83.0
##  9 comgra      Common… Quisca… L220… Union … 2020…       3  40.0 -83.0
## 10 blujay      Blue J… Cyanoc… L220… Union … 2020…       1  40.0 -83.0
## # … with 4 more variables: obsValid <lgl>, obsReviewed <lgl>,
## #   locationPrivate <lgl>, subId <chr>
```


### Frequency of observations at hotspots or regions

Obtain historical frequencies of bird occurrences at a given hotspot


```r
ebirdfreq(loctype = 'hotspots', loc = 'L196159')
```

```
## # A tibble: 9,600 x 4
##    comName                     monthQt   frequency sampleSize
##    <chr>                       <chr>         <dbl>      <dbl>
##  1 Snow Goose                  January-1     0             36
##  2 Greater White-fronted Goose January-1     0             36
##  3 Cackling Goose              January-1     0             36
##  4 Canada Goose                January-1     0             36
##  5 Cackling/Canada Goose       January-1     0             36
##  6 Trumpeter Swan              January-1     0             36
##  7 Wood Duck                   January-1     0.139         36
##  8 Blue-winged Teal            January-1     0             36
##  9 Cinnamon Teal               January-1     0             36
## 10 Blue-winged/Cinnamon Teal   January-1     0             36
## # … with 9,590 more rows
```

Same, but in wide format (for making bar charts)


```r
ebirdfreq(loctype = 'hotspots', loc = 'L196159', long = FALSE)
```

```
## # A tibble: 201 x 49
##    comName `January-1` `January-2` `January-3` `January-4` `February-1`
##    <chr>         <dbl>       <dbl>       <dbl>       <dbl>        <dbl>
##  1 Sample…      36         33          46         118           49     
##  2 Snow G…       0          0           0           0            0     
##  3 Greate…       0          0           0           0            0     
##  4 Cackli…       0          0           0           0            0     
##  5 Canada…       0          0.0303      0.0015      0.110        0.204 
##  6 Cackli…       0          0           0           0            0     
##  7 Trumpe…       0          0           0           0            0     
##  8 Wood D…       0.139      0.0303      0           0.0169       0.0408
##  9 Blue-w…       0          0           0           0            0     
## 10 Cinnam…       0          0           0           0            0     
## # … with 191 more rows, and 43 more variables: `February-2` <dbl>,
## #   `February-3` <dbl>, `February-4` <dbl>, `March-1` <dbl>,
## #   `March-2` <dbl>, `March-3` <dbl>, `March-4` <dbl>, `April-1` <dbl>,
## #   `April-2` <dbl>, `April-3` <dbl>, `April-4` <dbl>, `May-1` <dbl>,
## #   `May-2` <dbl>, `May-3` <dbl>, `May-4` <dbl>, `June-1` <dbl>,
## #   `June-2` <dbl>, `June-3` <dbl>, `June-4` <dbl>, `July-1` <dbl>,
## #   `July-2` <dbl>, `July-3` <dbl>, `July-4` <dbl>, `August-1` <dbl>,
## #   `August-2` <dbl>, `August-3` <dbl>, `August-4` <dbl>,
## #   `September-1` <dbl>, `September-2` <dbl>, `September-3` <dbl>,
## #   `September-4` <dbl>, `October-1` <dbl>, `October-2` <dbl>,
## #   `October-3` <dbl>, `October-4` <dbl>, `November-1` <dbl>,
## #   `November-2` <dbl>, `November-3` <dbl>, `November-4` <dbl>,
## #   `December-1` <dbl>, `December-2` <dbl>, `December-3` <dbl>,
## #   `December-4` <dbl>
```

Obtain frequency data for a given state


```r
ebirdfreq(loctype = 'states', loc = 'CA-BC')
```

```
## # A tibble: 36,144 x 4
##    comName                                    monthQt  frequency sampleSize
##    <chr>                                      <chr>        <dbl>      <dbl>
##  1 Fulvous Whistling-Duck                     January… 0              19662
##  2 Emperor Goose                              January… 0              19662
##  3 Snow Goose                                 January… 0.0301         19662
##  4 Ross's Goose                               January… 0              19662
##  5 Snow x Ross's Goose (hybrid)               January… 0              19662
##  6 Snow/Ross's Goose                          January… 0              19662
##  7 Swan Goose (Domestic type)                 January… 0.0000509      19662
##  8 Graylag x Swan Goose (Domestic type) (hyb… January… 0              19662
##  9 Greater White-fronted Goose                January… 0.00788        19662
## 10 Pink-footed Goose                          January… 0              19662
## # … with 36,134 more rows
```

Or county


```r
ebirdfreq(loctype = 'counties', loc = 'CA-BC-GV')
```

```
## # A tibble: 25,680 x 4
##    comName                                    monthQt  frequency sampleSize
##    <chr>                                      <chr>        <dbl>      <dbl>
##  1 Emperor Goose                              January…   0             6166
##  2 Snow Goose                                 January…   0.0686        6166
##  3 Ross's Goose                               January…   0             6166
##  4 Snow/Ross's Goose                          January…   0             6166
##  5 Greater White-fronted Goose                January…   0.00519       6166
##  6 Domestic goose sp. (Domestic type)         January…   0             6166
##  7 Brant                                      January…   0.0323        6166
##  8 Cackling Goose                             January…   0.0185        6166
##  9 Canada Goose                               January…   0.205         6166
## 10 Swan Goose (Domestic type) x Canada Goose… January…   0             6166
## # … with 25,670 more rows
```

Obtain frequency data within a range of years and months


```r
ebirdfreq(loctype = 'hotspots', loc = 'L196159', startyear = 2010,
          endyear = 2014, startmonth = 1, endmonth = 3)
```

```
## # A tibble: 3,792 x 4
##    comName                             monthQt   frequency sampleSize
##    <chr>                               <chr>         <dbl>      <dbl>
##  1 Canada Goose                        January-1       0           10
##  2 Wood Duck                           January-1       0.4         10
##  3 Northern Shoveler                   January-1       0.8         10
##  4 Gadwall                             January-1       0           10
##  5 Eurasian Wigeon                     January-1       0.4         10
##  6 American Wigeon                     January-1       1           10
##  7 Eurasian x American Wigeon (hybrid) January-1       0           10
##  8 Mallard                             January-1       1           10
##  9 Northern Pintail                    January-1       0           10
## 10 Green-winged Teal                   January-1       0           10
## # … with 3,782 more rows
```


### Recent notable sightings

Search for notable sightings at a given latitude and longitude


```r
ebirdnotable(lat = 42, lng = -70)
```

```
## # A tibble: 1,322 x 13
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 norbob      Northe… Colinu… L840… 43 2nd… 2020…       1  41.0 -72.0
##  2 monpar      Monk P… Myiops… L111… 584 So… 2020…       1  41.6 -72.8
##  3 buggna      Blue-g… Poliop… L997… 1063 S… 2020…       1  41.5 -72.9
##  4 merlin      Merlin  Falco … L152… Bates … 2020…       1  44.1 -70.2
##  5 louwat      Louisi… Parkes… L152… Henwoo… 2020…       1  43.1 -72.5
##  6 buggna      Blue-g… Poliop… L207… Moose … 2020…       1  42.1 -71.2
##  7 sancra      Sandhi… Antigo… L452… Bolton… 2020…       1  42.5 -71.6
##  8 vesspa      Vesper… Pooece… L418… McCart… 2020…       1  42.2 -71.3
##  9 buggna      Blue-g… Poliop… L418… McCart… 2020…       1  42.2 -71.3
## 10 amebit      Americ… Botaur… L392… North … 2020…       1  41.3 -70.1
## # … with 1,312 more rows, and 4 more variables: obsValid <lgl>,
## #   obsReviewed <lgl>, locationPrivate <lgl>, subId <chr>
```

or a region


```r
ebirdnotable(locID = 'US-NY-109')
```

```
## # A tibble: 51 x 13
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 y00478      Icelan… Larus … L353… Salt P… 2020…       1  42.5 -76.5
##  2 whcspa      White-… Zonotr… L137… Sapsuc… 2020…       1  42.5 -76.5
##  3 caster1     Caspia… Hydrop… L996… Myers … 2020…       1  42.5 -76.6
##  4 caster1     Caspia… Hydrop… L996… Myers … 2020…       1  42.5 -76.6
##  5 caster1     Caspia… Hydrop… L996… Myers … 2020…       1  42.5 -76.6
##  6 yelwar      Yellow… Setoph… L441… AviTra… 2020…       1  42.3 -76.4
##  7 caster1     Caspia… Hydrop… L996… Myers … 2020…       2  42.5 -76.6
##  8 caster1     Caspia… Hydrop… L353… Salt P… 2020…       1  42.5 -76.5
##  9 brwhaw      Broad-… Buteo … L441… AviTra… 2020…       2  42.3 -76.4
## 10 houwre      House … Troglo… L997… Ilion   2020…       1  42.4 -76.5
## # … with 41 more rows, and 4 more variables: obsValid <lgl>,
## #   obsReviewed <lgl>, locationPrivate <lgl>, subId <chr>
```

### Historic Observations

Obtain a list of species reported on a specific date in a given region 


```r
ebirdhistorical(loc = 'US-VA-003', date = '2019-02-14', max = 10)
```

```
## # A tibble: 10 x 13
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 cangoo      Canada… Branta… L139… Lickin… 2019…      30  38.1 -78.7
##  2 mallar3     Mallard Anas p… L139… Lickin… 2019…       5  38.1 -78.7
##  3 gnwtea      Green-… Anas c… L139… Lickin… 2019…       8  38.1 -78.7
##  4 killde      Killde… Charad… L139… Lickin… 2019…       1  38.1 -78.7
##  5 baleag      Bald E… Haliae… L139… Lickin… 2019…       1  38.1 -78.7
##  6 belkin1     Belted… Megace… L139… Lickin… 2019…       1  38.1 -78.7
##  7 carwre      Caroli… Thryot… L139… Lickin… 2019…       1  38.1 -78.7
##  8 whtspa      White-… Zonotr… L139… Lickin… 2019…       2  38.1 -78.7
##  9 norcar      Northe… Cardin… L139… Lickin… 2019…       1  38.1 -78.7
## 10 canvas      Canvas… Aythya… L331… Montic… 2019…      19  38.0 -78.5
## # … with 4 more variables: obsValid <lgl>, obsReviewed <lgl>,
## #   locationPrivate <lgl>, subId <chr>
```

or a hotspot


```r
ebirdhistorical(loc = 'L196159', date = '2019-02-14', fieldSet = 'full')
```

```
## # A tibble: 14 x 27
##    speciesCode comName sciName locId locName obsDt howMany   lat   lng
##    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl>
##  1 annhum      Anna's… Calypt… L196… Vancou… 2019…       4  49.3 -123.
##  2 ribgul      Ring-b… Larus … L196… Vancou… 2019…       4  49.3 -123.
##  3 glwgul      Glauco… Larus … L196… Vancou… 2019…      29  49.3 -123.
##  4 norcro      Northw… Corvus… L196… Vancou… 2019…     100  49.3 -123.
##  5 bkcchi      Black-… Poecil… L196… Vancou… 2019…      16  49.3 -123.
##  6 bushti      Bushtit Psaltr… L196… Vancou… 2019…      20  49.3 -123.
##  7 pacwre1     Pacifi… Troglo… L196… Vancou… 2019…       1  49.3 -123.
##  8 houfin      House … Haemor… L196… Vancou… 2019…       2  49.3 -123.
##  9 purfin      Purple… Haemor… L196… Vancou… 2019…       3  49.3 -123.
## 10 amegfi      Americ… Spinus… L196… Vancou… 2019…      15  49.3 -123.
## 11 daejun      Dark-e… Junco … L196… Vancou… 2019…      37  49.3 -123.
## 12 sonspa      Song S… Melosp… L196… Vancou… 2019…      12  49.3 -123.
## 13 spotow      Spotte… Pipilo… L196… Vancou… 2019…       1  49.3 -123.
## 14 rewbla      Red-wi… Agelai… L196… Vancou… 2019…       6  49.3 -123.
## # … with 18 more variables: obsValid <lgl>, obsReviewed <lgl>,
## #   locationPrivate <lgl>, subId <chr>, subnational2Code <chr>,
## #   subnational2Name <chr>, subnational1Code <chr>,
## #   subnational1Name <chr>, countryCode <chr>, countryName <chr>,
## #   userDisplayName <chr>, obsId <chr>, checklistId <chr>,
## #   presenceNoted <lgl>, hasComments <lgl>, firstName <chr>,
## #   lastName <chr>, hasRichMedia <lgl>
```

### eBird taxonomy

Returns a data.frame of all species in the eBird taxonomy for the given parameter inputs


```r
ebirdtaxonomy()
```

```
## # A tibble: 16,513 x 14
##    sciName comName speciesCode category taxonOrder bandingCodes
##    <chr>   <chr>   <chr>       <chr>         <dbl> <chr>       
##  1 Struth… Common… ostric2     species           1 <NA>        
##  2 Struth… Somali… ostric3     species           6 <NA>        
##  3 Struth… Common… y00934      slash             7 <NA>        
##  4 Rhea a… Greate… grerhe1     species           8 <NA>        
##  5 Rhea p… Lesser… lesrhe2     species          14 <NA>        
##  6 Rhea p… Lesser… lesrhe4     issf             15 <NA>        
##  7 Rhea p… Lesser… lesrhe3     issf             18 <NA>        
##  8 Nothoc… Tawny-… tabtin1     species          19 <NA>        
##  9 Nothoc… Highla… higtin1     species          20 HITI        
## 10 Nothoc… Highla… higtin2     issf             21 <NA>        
## # … with 16,503 more rows, and 8 more variables: comNameCodes <chr>,
## #   sciNameCodes <chr>, order <chr>, familyComName <chr>,
## #   familySciName <chr>, reportAs <chr>, extinct <lgl>, extinctYear <int>
```

Search for hybrid species only


```r
ebirdtaxonomy(cat = "hybrid")
```

```
## # A tibble: 462 x 11
##    sciName comName speciesCode category taxonOrder bandingCodes
##    <chr>   <chr>   <chr>       <chr>         <dbl> <chr>       
##  1 Dendro… Spotte… x00721      hybrid          219 <NA>        
##  2 Dendro… Black-… x00775      hybrid          224 <NA>        
##  3 Dendro… White-… x00938      hybrid          226 <NA>        
##  4 Dendro… Black-… x00875      hybrid          227 <NA>        
##  5 Anser … Snow x… sxrgoo1     hybrid          244 SRGH        
##  6 Anser … Grayla… x00776      hybrid          252 <NA>        
##  7 Anser … Bar-he… x00755      hybrid          260 <NA>        
##  8 Anser … Snow x… x00627      hybrid          261 <NA>        
##  9 Anser … Snow G… x00685      hybrid          281 <NA>        
## 10 Anser … Pink-f… x00756      hybrid          283 <NA>        
## # … with 452 more rows, and 5 more variables: comNameCodes <chr>,
## #   sciNameCodes <chr>, order <chr>, familyComName <chr>,
## #   familySciName <chr>
```

## Information on a given region or hotspot

Obtain detailed information on any valid eBird region


```r
ebirdregioninfo("CA-BC-GV")
```

```
## # A tibble: 1 x 5
##   region                                     minX  maxX  minY  maxY
##   <chr>                                     <dbl> <dbl> <dbl> <dbl>
## 1 Metro Vancouver, British Columbia, Canada -123. -122.  49.0  49.6
```

or hotspot


```r
ebirdregioninfo("L196159")
```

```
## # A tibble: 1 x 16
##   locId name  latitude longitude countryCode countryName subnational1Name
##   <chr> <chr>    <dbl>     <dbl> <chr>       <chr>       <chr>           
## 1 L196… Vanc…     49.3     -123. CA          Canada      British Columbia
## # … with 9 more variables: subnational1Code <chr>, subnational2Code <chr>,
## #   subnational2Name <chr>, isHotspot <lgl>, locName <chr>, lat <dbl>,
## #   lng <dbl>, hierarchicalName <chr>, locID <chr>
```


Obtain a list of eBird codes for all species recorded in a region

```r
ebirdregionspecies("GB-ENG-LND")
```

```
## # A tibble: 304 x 1
##    speciesCode
##    <chr>      
##  1 bahgoo     
##  2 snogoo     
##  3 gragoo     
##  4 gwfgoo     
##  5 tunbeg1    
##  6 pifgoo     
##  7 brant      
##  8 bargoo     
##  9 cangoo     
## 10 rebgoo1    
## # ... with 294 more rows
```

or a hotspot

```r
ebirdregionspecies("L5803024")
```

```
## # A tibble: 156 x 1
## speciesCode
## <chr>
##   1 gragoo
## 2 gwfgoo
## 3 bargoo
## 4 cangoo
## 5 mutswa
## 6 egygoo
## 7 comshe
## 8 manduc
## 9 gargan
## 10 norsho
## # ... with 146 more rows
```

## Checklist Feed

Obtain a list of checklists submitted on a given date at a region or hotspot


```r
ebirdchecklistfeed(loc = "L207391", date = "2020-03-24", max = 5)
```

```
## # A tibble: 5 x 8
##   locId  subId  userDisplayName numSpecies obsDt obsTime subID loc         
##   <chr>  <chr>  <chr>                <int> <chr> <chr>   <chr> <chr>       
## 1 L2073… S6617… David Wood              10 24 M… 14:47   S661… L207391,Mt.…
## 2 L2073… S6617… Sofia Prado-Ir…         15 24 M… 14:31   S661… L207391,Mt.…
## 3 L2073… S6619… Jeffrey Gantz           19 24 M… 13:30   S661… L207391,Mt.…
## 4 L2073… S6617… Ann Gurka               21 24 M… 13:00   S661… L207391,Mt.…
## 5 L2073… S6618… Jason Barcus            24 24 M… 07:30   S661… L207391,Mt.…
```
