context("ebirdloc")

test_that("ebirdloc works correctly", {
  out <- ebirdloc(c('L99381','L99382'))
  expect_is(out, "data.frame")
  expect_equal(dim(out), c(112,11))
  expect_is(out$comName, "character")
  expect_is(out$howMany, "numeric")
  expect_is(ebirdloc('L99381', 'larus delawarensis', provisional=TRUE, hotspot=TRUE), "data.frame")
  expect_equal(nrow(ebirdloc('L99381', 'larus delawarensis', provisional=TRUE, hotspot=TRUE)), 1)
  expect_error(ebirdloc())
  expect_error(ebirdloc(species = "asdf"))
  expect_error(ebirdloc(locID = "asdfasdf", species = "asdf"))
  expect_error(ebirdloc(locID = "L99381", species = "asdf"))
  expect_error(ebirdloc(locID = "L99381", species = "Larus"))
})