context("ebirdloc")

test_that("ebirdloc works correctly", {
  out <- ebirdloc(c('L99381','L99382'))
  expect_is(out, "data.frame")
  expect_equal(ncol(out), 11)
  expect_is(out$comName, "character")
  expect_is(out$howMany, "integer")
  expect_is(ebirdloc('L99381', 'larus delawarensis', provisional=TRUE), "data.frame")
  expect_error(ebirdloc())
  expect_error(ebirdloc(species = "asdf"))
  expect_warning(ebirdloc(locID = "asdfasdf", species = "asdf"))
  
  simpler <- ebirdloc('L99381', max = 1, simple = TRUE)
  lesssimpler <- ebirdloc('L99381', max = 1, simple = FALSE)
  expect_less_than(NCOL(simpler), 15)
  expect_that(NCOL(simpler), not(is_less_than(8)))
  expect_less_than(NCOL(lesssimpler), 30)
  expect_that(NCOL(lesssimpler), not(is_less_than(10)))
})
